# Generated by Django 3.1.2 on 2020-10-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic_circle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
