# Generated by Django 3.1.2 on 2020-10-09 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magic_circle', '0003_magiccircle'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiccircle',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
