# Generated by Django 3.1.2 on 2020-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_circle', '0004_magiccircle_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magiccircle',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='magiccircle',
            name='circle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='magiccircle',
            name='corner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='magiccircle',
            name='line',
            field=models.IntegerField(default=0),
        ),
    ]
